os: linux

language: java

#cache:
#  directories:
#    - $HOME/.gradle/caches/
#    - $HOME/.gradle/wrapper/

jobs:
  include:
    - stage: test
      jdk:
        - oraclejdk11
        - openjdk11
#      script: ./gradlew clean test
    cache:
      directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
